import { useState } from 'react'
import './App.css'

const platypusFacts = [
	"The word platypus comes from Greek platys, meaning flat, and pous, meaning foot.",
	"Platypuses are one of only five species of mammals that lay eggs.",
	"Male platypuses have venomous spurs on their hind legs.",
	"Platypuses can detect electric fields generated by their prey using their bills.",
	"A baby platypus is called a puggle.",
	"Platypuses don't have stomachs. Their esophagus connects directly to their intestines.",
	"Platypuses close their eyes and ears while swimming and rely on their bill to navigate.",
	"The platypus is the animal emblem of New South Wales, Australia.",
	"Platypuses can store up to 900 insects in their cheek pouches.",
	"A platypus can consume its own body weight in food in a 24 hour period."
]

function App() {
	const [fact, setFact] = useState(platypusFacts[0])

	const getNewFact = () => {
		let randomIndex = Math.floor(Math.random() * platypusFacts.length)
		while (platypusFacts[randomIndex] === fact) {
			randomIndex = Math.floor(Math.random() * platypusFacts.length)
		}
		setFact(platypusFacts[randomIndex])
	}

	return (
		<>
			<div className='content'>
				<h1>PLATYPUS FACTS</h1>

				<div className='fact-container'>
					<p>{fact}</p>
				</div>

				<div className="btn" onClick={getNewFact}>GET A NEW FACT</div>
			</div>
		</>
	)
}

export default App
